[Issue #6] defile paris page creation
jlm2017/campagne.jlm2017.fr pull request #7
Opened 2017-01-20 22:02 UTC by alexthevenot

Hello,

Je fais un test de création de page (défilé de Paris).
Je suis pas du tout sûr de moi donc les commentaires sont les bienvenus.
Et je ne sais pas non plus où trouver les infos concernant les directs ? Pour créer les fichiers .yml
Ah et je ne sais pas non plus comment visualiser la page nouvellement créée avec la bonne mise en page ?

Si c'est bon j'attaque les autres!
A plus

2017-01-23 16:16 UTC, jillro requested changes
Merci beaucoup ! Je n'arrive cependant pas à build (`Could not locate the included file 'paris_defile_menu.html'`).

2017-01-23 16:18 UTC, guilro commented on _evenements/paris_defile/index.html
> +        {% assign direct='direct_paris_defile' %}
Même si le code HTML est commenté le code liquid est inteprété. S'il n'y a pas de déroulé par grave, on enlève ces lignes ;)

2017-01-25 08:28 UTC, alexthevenot commented
Ok je vire le code liquid ! 
J'ai moyen de builder de mon côté ? Je ne sais pas comment m'y prendre

2017-01-25 09:15 UTC, alexthevenot commented
Bon bah j'ai fait les autres pages sur la même branche finalement.
Quelques détails.. certains évènements n'ont pas  de # associé, j'ai mis JLM2017 par défaut.
Certains évènements n'ont pas de photo.. je n'ai rien mis.
La page pour la convention de Lille était déjà faite.
Et pour le Lamentin il y'a déjà une page qui groupe un peu le gosier et le lamentin. Est ce qu'il faut splitter, et créer une page spéciale lamentin ?
Tchou !

2017-01-25 09:29 UTC, guilro commented
Merci ! J'ai ajouté des instructions sur le README.md du dépôt pour expliquer comment build le site en local.

2017-01-25 09:29 UTC, jillro approved these changes

2017-01-25 09:36 UTC, jillro requested changes
Quelques petits trucs à changer avant que ça fonctionne parfaitement !

2017-01-25 09:36 UTC, guilro commented on _evenements/boulogne-sur-mer/index.html
> +      <iframe width="1280" height="720" src="https://www.youtube.com/watch?v=L0zosTKacRs" frameborder="0" allowfullscreen></iframe>
L'URL n'est pas correct, elle doit être de la forme youtube.com/embed/identifiant?rel=0 (boutons "Partager" > "Intégrer" sur Youtube)

2017-01-25 09:36 UTC, guilro commented on _evenements/boulogne-sur-mer/index.html
> +    <a class="twitter-timeline"  href="https://twitter.com/hashtag/JLM2017" data-widget-id="816992721114136576">Tweets sur #JLM2017</a>
Il faudrait créer pour chaque hashtag un widget Twitter (cela peut se faire depuis n'importe quel compte twitter). Changer le hashtag dans le href ne suffit pas, le hashtag affiché dépend du `data-widget-id`

2017-01-25 09:36 UTC, guilro commented on _evenements/paris_defile/index.html
> +      <iframe width="1280" height="720" src="https://www.youtube.com/watch?v=zyEDOTEZyPM" frameborder="0" allowfullscreen></iframe>
Pareil :)

2017-01-25 09:36 UTC, guilro commented on _evenements/paris_defile/index.html
> +    <a class="twitter-timeline"  href="https://twitter.com/hashtag/insoumis5juin" data-widget-id="816992721114136576">Tweets sur #insoumis5juin</a>
Pareil :)

2017-01-25 09:36 UTC, guilro commented on _evenements/toulouse_pique-nique/index.html
> +      <iframe width="1280" height="720" src="https://www.youtube.com/watch?v=DJ8hQ77nbw8" frameborder="0" allowfullscreen></iframe>
Pareil :)

2017-01-25 09:36 UTC, guilro commented on _evenements/toulouse_pique-nique/index.html
> +    <a class="twitter-timeline"  href="https://twitter.com/hashtag/JLM2017" data-widget-id="816992721114136576">Tweets sur #JLM2017</a>
Pareil :)

2017-01-25 09:37 UTC, guilro commented
Si tu arrives à build et à faire ces changements c'est super =D !

2017-01-25 10:16 UTC, alexthevenot commented
Aaah c'est plus sympa quand on arrive à voir ce que l'on fait ! Merci pour les instructions pour builder.
ça devrait être bon ce coup ci :)

2017-01-25 10:19 UTC, guilro commented
Parfait ! Merci beaucoup, c'est génial !

2017-01-25 10:19 UTC, jillro approved these changes

2017-01-25 10:20 UTC, merged